# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03316ff8d0f962fec699890dcc3ff76bf4bb69847d9281991156afb40d85d9e130e9518202d1f99abd5c09d179b2ba1697430981620310148d63c1559189099f

test:
  secret_key_base: 7ba555afcf918dedeed694d9ceacdc57dd6b7fad4e114a55f4c4b75b95bf3414877fff0fc290b16f686cecb9cf39bc2e5109f616f230ec384ea957a835614f7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
